apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: LoadBalancer  # Add this line to specify the LoadBalancer type
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: 7007  # Ensure this matches the port your application is listening on
